import os
import streamlit as st
from google import genai
from google.genai.errors import APIError

# Define the standard model name compatible with the google-genai SDK
DEFAULT_MODEL = "gemini-2.5-flash"

def _get_gemini_client() -> genai.Client:
    """
    Initializes and returns the official Google GenAI client securely.
    Checks Streamlit secrets first, falling back to OS environment variables.
    Raises a ValueError if no API key is found.
    """
    api_key = None
    
    # 1. Try fetching from Streamlit secrets (for Streamlit Community Cloud)
    try:
        if "GEMINI_API_KEY" in st.secrets:
            api_key = st.secrets["GEMINI_API_KEY"]
        elif "GOOGLE_API_KEY" in st.secrets:
            api_key = st.secrets["GOOGLE_API_KEY"]
    except Exception:
        # Streamlit secrets might not be configured locally or in certain test environments
        pass
        
    # 2. Fall back to environment variables (for local development or Google Colab)
    if not api_key:
        api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
        
    if not api_key:
        raise ValueError(
            "Gemini API key not found! Please configure it in your Streamlit secrets "
            "(.streamlit/secrets.toml) or set the GEMINI_API_KEY environment variable."
        )
        
    return genai.Client(api_key=api_key)


def generate_dataset_summary(dataset_summary: dict) -> str:
    """
    Explains what the dataset appears to represent, highlights important columns,
    and explains the structure in beginner-friendly language using Gemini.
    
    Parameters:
    -----------
    dataset_summary : dict
        The deterministic statistical summary dictionary generated by data_analyzer.py.
        
    Returns:
    --------
    str
        A natural-language explanation of the dataset.
    """
    if not dataset_summary or dataset_summary.get("is_empty", True):
        return "The dataset is empty or invalid, so a summary cannot be generated."

    try:
        client = _get_gemini_client()
        
        prompt = f"""
        You are an expert data science assistant. Analyze the following statistical dataset summary 
        computed by Pandas and provide a clear, beginner-friendly explanation.

        Dataset Metadata:
        - Total Rows: {dataset_summary.get('row_count')}
        - Total Columns: {dataset_summary.get('col_count')}
        - Columns & Data Types: {dataset_summary.get('dtypes')}
        - Numerical Columns: {dataset_summary.get('numerical_cols')}
        - Categorical Columns: {dataset_summary.get('categorical_cols')}
        - Missing Values Overview: \n{dataset_summary.get('missing_summary').to_string() if not dataset_summary.get('missing_summary').empty else 'None'}

        Please provide:
        1. **What this dataset appears to represent:** Deduce the real-world domain or context based on column names and types.
        2. **Important Columns:** Highlight key features and explain what role they play.
        3. **Beginner-Friendly Breakdown:** Explain the layout simply so a student or non-technical stakeholder can instantly understand it.
        
        Keep your tone encouraging, professional, and clear. Do not invent details not supported by the summary.
        """

        response = client.models.generate_content(
            model=DEFAULT_MODEL,
            contents=prompt
        )
        
        if not response or not response.text:
            return "Received an empty response from Gemini while generating the dataset summary."
            
        return response.text

    except ValueError as ve:
        return f"Configuration Error: {str(ve)}"
    except APIError as ae:
        return f"Gemini API request failed: {str(ae)}"
    except Exception as e:
        return f"An unexpected error occurred while generating the dataset summary: {str(e)}"


def generate_insights(dataset_summary: dict) -> str:
    """
    Identifies interesting patterns or data anomalies strictly from the computed summary.
    Never invents values and bases all claims on the supplied statistics.
    
    Parameters:
    -----------
    dataset_summary : dict
        The deterministic statistical summary dictionary.
        
    Returns:
    --------
    str
        A markdown-formatted string highlighting patterns, distributions, and anomalies.
    """
    if not dataset_summary or dataset_summary.get("is_empty", True):
        return "No dataset summary available to extract insights."

    try:
        client = _get_gemini_client()
        
        prompt = f"""
        You are an analytical data science assistant. Based STRICTLY on the pre-computed dataset statistics 
        provided below, identify interesting patterns, notable value frequencies, missing data observations, 
        or distributional characteristics.

        Computed Statistics:
        - Numerical Descriptive Stats: {dataset_summary.get('numerical_stats')}
        - Categorical Top Value Frequencies: {dataset_summary.get('categorical_top_values')}
        - Duplicate Rows Count: {dataset_summary.get('duplicate_count')}
        - Missing Summary: \n{dataset_summary.get('missing_summary').to_string() if not dataset_summary.get('missing_summary').empty else 'None'}

        Strict Rules:
        - Do NOT invent or hallucinate data values, means, or frequencies not present in the summary above.
        - Point out concrete observations (e.g., high missing percentages, skewed stats, dominant categories).
        """

        response = client.models.generate_content(
            model=DEFAULT_MODEL,
            contents=prompt
        )
        
        if not response or not response.text:
            return "Received an empty response from Gemini while generating insights."
            
        return response.text

    except ValueError as ve:
        return f"Configuration Error: {str(ve)}"
    except APIError as ae:
        return f"Gemini API request failed: {str(ae)}"
    except Exception as e:
        return f"An unexpected error occurred while generating insights: {str(e)}"


def generate_analysis_questions(dataset_summary: dict) -> str:
    """
    Generates structured analysis questions that could be investigated using the dataset,
    categorized into Beginner, Intermediate, and Advanced tiers.
    
    Parameters:
    -----------
    dataset_summary : dict
        The deterministic statistical summary dictionary.
        
    Returns:
    --------
    str
        Categorized analysis questions formatted in markdown.
    """
    if not dataset_summary or dataset_summary.get("is_empty", True):
        return "No dataset available to generate analysis questions."

    try:
        client = _get_gemini_client()
        
        prompt = f"""
        You are a senior data mentor guiding a college student on a data analysis project. 
        Based on the dataset structure and columns provided below, generate valuable analytical questions 
        that can be explored using this data.

        Dataset Structure:
        - Columns: {dataset_summary.get('columns')}
        - Data Types: {dataset_summary.get('dtypes')}
        - Numerical Features: {dataset_summary.get('numerical_cols')}
        - Categorical Features: {dataset_summary.get('categorical_cols')}

        Categorize the questions strictly into three headings:
        1. **Beginner** (Focus on basic aggregations, single-column distributions, and filtering)
        2. **Intermediate** (Focus on group-bys, bivariate relationships, correlations, and comparisons)
        3. **Advanced** (Focus on predictive modeling concepts, anomaly detection, segmentation, or multi-factor trends)

        Ensure the questions are specifically tailored to this dataset's column names and domain, rather than being generic placeholders.
        """

        response = client.models.generate_content(
            model=DEFAULT_MODEL,
            contents=prompt
        )
        
        if not response or not response.text:
            return "Received an empty response from Gemini while generating analysis questions."
            
        return response.text

    except ValueError as ve:
        return f"Configuration Error: {str(ve)}"

def answer_data_query(analysis_summary: dict, user_question: str) -> str:
    """
    Sends the dataset summary context and a user question to Gemini
    to answer natural language queries about the data.
    """
    try:
        client = get_gemini_client()
        prompt = f"""
        You are DataLens AI, an expert data science assistant.
        Here is the statistical summary of the dataset:
        {analysis_summary}
        
        The user is asking a question about this dataset:
        "{user_question}"
        
        Provide a clear, concise, and accurate answer based strictly on the provided statistical summary. If numerical calculation is required that isn't provided, explain what it means or how to find it.
        """
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt
        )
        return response.text
    except Exception as e:
        return f"Error generating AI response: {str(e)}"   
    

    
    except APIError as ae:
        return f"Gemini API request failed: {str(ae)}"
    except Exception as e:
        return f"An unexpected error occurred while generating analysis questions: {str(e)}"
        
